
### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "jwttest@example.com",
  "password": "password123"
}


###
GET http://localhost:3000/api/availability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Y5ZjIyNy01YTllLTQyNmYtOGY3ZS02YTI5MmI5MjA4ZDkiLCJpYXQiOjE3ODQxMzM3ODAsImV4cCI6MTc4NDEzNzM4MH0.vS3jps7CangG4Dqns9K8y8dd2XgIF3BcTc0J9fQm8ng

###
PATCH http://localhost:3000/api/availability/d18f3a5a-cc43-4d95-b135-a18720819b33
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Y5ZjIyNy01YTllLTQyNmYtOGY3ZS02YTI5MmI5MjA4ZDkiLCJpYXQiOjE3ODQxMzM3ODAsImV4cCI6MTc4NDEzNzM4MH0.vS3jps7CangG4Dqns9K8y8dd2XgIF3BcTc0J9fQm8ng

{
  "dayOfWeek": 2,
  "startTime": "11:00",
  "endTime": "17:00"
}

### Delete availability
DELETE http://localhost:3000/api/availability/d18f3a5a-cc43-4d95-b135-a18720819b33
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxN2Y5ZjIyNy01YTllLTQyNmYtOGY3ZS02YTI5MmI5MjA4ZDkiLCJpYXQiOjE3ODQxMzM3ODAsImV4cCI6MTc4NDEzNzM4MH0.vS3jps7CangG4Dqns9K8y8dd2XgIF3BcTc0J9fQm8ng

###
POST http://localhost:3000/api/users/advait/bookings
Content-Type: application/json

{
  "guestName": "John Doe",
  "guestEmail": "john@example.com",
  "startsAt": "2026-07-20T09:00:00-04:00",
  "endsAt": "2026-07-20T09:30:00-04:00"
}

###
GET http://localhost:3000/api/users/advait/slots?date=2026-07-20