CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  name VARCHAR(255) NOT NULL,

  email VARCHAR(255) NOT NULL UNIQUE,

  password_hash TEXT NOT NULL,

  slug VARCHAR(100) NOT NULL UNIQUE,

  timezone VARCHAR(100) NOT NULL DEFAULT 'America/New_York',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);